[DB_SERVER]
Server=127.0.0.1
Database=wxz2c_game_fanji
Port=3306
Username=root
Password=GQMPevGcoswvnMyU

;下面用于从mysql中获取跨服公共资料，主要是ConveyServers
[DB_SERVER_PUB]
Server=127.0.0.1
Database=wxz_kf
Port=3306
Username=root
Password=GQMPevGcoswvnMyU

[Redis]
;连接Redis高速缓存 推荐使用
;如果共用Redis DBNAME不能相同
OPEN=1
Server=127.0.0.1
Port=6379
Pass=